/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LocalRouteImport } from './routes/local'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TipsIndexRouteImport } from './routes/tips.index'
import { Route as PolicyIndexRouteImport } from './routes/policy.index'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as HomeIndexRouteImport } from './routes/home.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CareIndexRouteImport } from './routes/care.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TipsTipIdRouteImport } from './routes/tips.$tipId'
import { Route as SeniorHomeRouteImport } from './routes/senior.home'
import { Route as PolicySlugRouteImport } from './routes/policy.$slug'
import { Route as PartnerTasksRouteImport } from './routes/partner.tasks'
import { Route as InviteGuardianRouteImport } from './routes/invite.guardian'
import { Route as HomeSettingsRouteImport } from './routes/home.settings'
import { Route as HomePasskeysRouteImport } from './routes/home.passkeys'
import { Route as HomeMeRouteImport } from './routes/home.me'
import { Route as HomeInviteRouteImport } from './routes/home.invite'
import { Route as GuardianSettingsRouteImport } from './routes/guardian.settings'
import { Route as GuardianMedicationsRouteImport } from './routes/guardian.medications'
import { Route as GuardianDashboardRouteImport } from './routes/guardian.dashboard'
import { Route as GuardianCheckInRouteImport } from './routes/guardian.check-in'
import { Route as GuardianAlertsRouteImport } from './routes/guardian.alerts'
import { Route as CommunityWriteRouteImport } from './routes/community.write'
import { Route as AdminVoiceTestRouteImport } from './routes/admin.voice-test'
import { Route as AdminTipsRouteImport } from './routes/admin.tips'
import { Route as AdminSiteConfigRouteImport } from './routes/admin.site-config'
import { Route as AdminOrganizationPipelineRouteImport } from './routes/admin.organization-pipeline'
import { Route as AdminInvestorKpiRouteImport } from './routes/admin.investor-kpi'
import { Route as AdminIngestRouteImport } from './routes/admin.ingest'
import { Route as AdminEmotionRecRouteImport } from './routes/admin.emotion-rec'
import { Route as AdminAskLogsRouteImport } from './routes/admin.ask-logs'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminAgenciesRouteImport } from './routes/admin.agencies'
import { Route as HomeMessagesIndexRouteImport } from './routes/home.messages.index'
import { Route as HomeMessagesPartnerIdRouteImport } from './routes/home.messages.$partnerId'
import { Route as CommunityPostPostIdRouteImport } from './routes/community.post.$postId'
import { Route as CommunityCSlugRouteImport } from './routes/community.c.$slug'
import { Route as AdminTipsTipIdRouteImport } from './routes/admin.tips.$tipId'
import { Route as ApiPublicTwilioStatusRouteImport } from './routes/api/public/twilio.status'
import { Route as ApiPublicTwilioRecordingRouteImport } from './routes/api/public/twilio.recording'
import { Route as ApiPublicSmsVerifyCodeRouteImport } from './routes/api/public/sms.verify-code'
import { Route as ApiPublicSmsSendCodeRouteImport } from './routes/api/public/sms.send-code'
import { Route as ApiPublicSmsInboundRouteImport } from './routes/api/public/sms.inbound'
import { Route as ApiPublicOpenaiToolRouteImport } from './routes/api/public/openai.tool'
import { Route as ApiPublicOpenaiSessionRouteImport } from './routes/api/public/openai.session'
import { Route as ApiPublicIngestRunRouteImport } from './routes/api/public/ingest/run'
import { Route as ApiPublicCommunityAutoreactRouteImport } from './routes/api/public/community/autoreact'
import { Route as ApiPublicCommunityAutopostRouteImport } from './routes/api/public/community/autopost'
import { Route as ApiPublicCommunityAutocommentRouteImport } from './routes/api/public/community/autocomment'
import { Route as ApiInternalRulesRunRouteImport } from './routes/api/internal/rules.run'
import { Route as ApiInternalNotificationsDispatchRouteImport } from './routes/api/internal/notifications.dispatch'
import { Route as ApiInternalExtractionRunRouteImport } from './routes/api/internal/extraction.run'
import { Route as ApiInternalCallJobsRunRouteImport } from './routes/api/internal/call-jobs.run'
import { Route as ApiPublicTwilioTwimlJobIdRouteImport } from './routes/api/public/twilio.twiml.$jobId'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsIndexRoute = TipsIndexRouteImport.update({
  id: '/tips/',
  path: '/tips/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyIndexRoute = PolicyIndexRouteImport.update({
  id: '/policy/',
  path: '/policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareIndexRoute = CareIndexRouteImport.update({
  id: '/care/',
  path: '/care/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TipsTipIdRoute = TipsTipIdRouteImport.update({
  id: '/tips/$tipId',
  path: '/tips/$tipId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeniorHomeRoute = SeniorHomeRouteImport.update({
  id: '/senior/home',
  path: '/senior/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicySlugRoute = PolicySlugRouteImport.update({
  id: '/policy/$slug',
  path: '/policy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerTasksRoute = PartnerTasksRouteImport.update({
  id: '/partner/tasks',
  path: '/partner/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteGuardianRoute = InviteGuardianRouteImport.update({
  id: '/invite/guardian',
  path: '/invite/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSettingsRoute = HomeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HomeRoute,
} as any)
const HomePasskeysRoute = HomePasskeysRouteImport.update({
  id: '/passkeys',
  path: '/passkeys',
  getParentRoute: () => HomeRoute,
} as any)
const HomeMeRoute = HomeMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => HomeRoute,
} as any)
const HomeInviteRoute = HomeInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => HomeRoute,
} as any)
const GuardianSettingsRoute = GuardianSettingsRouteImport.update({
  id: '/guardian/settings',
  path: '/guardian/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianMedicationsRoute = GuardianMedicationsRouteImport.update({
  id: '/guardian/medications',
  path: '/guardian/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianDashboardRoute = GuardianDashboardRouteImport.update({
  id: '/guardian/dashboard',
  path: '/guardian/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianCheckInRoute = GuardianCheckInRouteImport.update({
  id: '/guardian/check-in',
  path: '/guardian/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianAlertsRoute = GuardianAlertsRouteImport.update({
  id: '/guardian/alerts',
  path: '/guardian/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityWriteRoute = CommunityWriteRouteImport.update({
  id: '/community/write',
  path: '/community/write',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVoiceTestRoute = AdminVoiceTestRouteImport.update({
  id: '/voice-test',
  path: '/voice-test',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTipsRoute = AdminTipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteConfigRoute = AdminSiteConfigRouteImport.update({
  id: '/site-config',
  path: '/site-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationPipelineRoute =
  AdminOrganizationPipelineRouteImport.update({
    id: '/organization-pipeline',
    path: '/organization-pipeline',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInvestorKpiRoute = AdminInvestorKpiRouteImport.update({
  id: '/investor-kpi',
  path: '/investor-kpi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIngestRoute = AdminIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmotionRecRoute = AdminEmotionRecRouteImport.update({
  id: '/emotion-rec',
  path: '/emotion-rec',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAskLogsRoute = AdminAskLogsRouteImport.update({
  id: '/ask-logs',
  path: '/ask-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgenciesRoute = AdminAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AdminRoute,
} as any)
const HomeMessagesIndexRoute = HomeMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeMessagesPartnerIdRoute = HomeMessagesPartnerIdRouteImport.update({
  id: '/messages/$partnerId',
  path: '/messages/$partnerId',
  getParentRoute: () => HomeRoute,
} as any)
const CommunityPostPostIdRoute = CommunityPostPostIdRouteImport.update({
  id: '/community/post/$postId',
  path: '/community/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityCSlugRoute = CommunityCSlugRouteImport.update({
  id: '/community/c/$slug',
  path: '/community/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTipsTipIdRoute = AdminTipsTipIdRouteImport.update({
  id: '/$tipId',
  path: '/$tipId',
  getParentRoute: () => AdminTipsRoute,
} as any)
const ApiPublicTwilioStatusRoute = ApiPublicTwilioStatusRouteImport.update({
  id: '/api/public/twilio/status',
  path: '/api/public/twilio/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioRecordingRoute =
  ApiPublicTwilioRecordingRouteImport.update({
    id: '/api/public/twilio/recording',
    path: '/api/public/twilio/recording',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSmsVerifyCodeRoute = ApiPublicSmsVerifyCodeRouteImport.update({
  id: '/api/public/sms/verify-code',
  path: '/api/public/sms/verify-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSmsSendCodeRoute = ApiPublicSmsSendCodeRouteImport.update({
  id: '/api/public/sms/send-code',
  path: '/api/public/sms/send-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSmsInboundRoute = ApiPublicSmsInboundRouteImport.update({
  id: '/api/public/sms/inbound',
  path: '/api/public/sms/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpenaiToolRoute = ApiPublicOpenaiToolRouteImport.update({
  id: '/api/public/openai/tool',
  path: '/api/public/openai/tool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpenaiSessionRoute = ApiPublicOpenaiSessionRouteImport.update({
  id: '/api/public/openai/session',
  path: '/api/public/openai/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRunRoute = ApiPublicIngestRunRouteImport.update({
  id: '/api/public/ingest/run',
  path: '/api/public/ingest/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCommunityAutoreactRoute =
  ApiPublicCommunityAutoreactRouteImport.update({
    id: '/api/public/community/autoreact',
    path: '/api/public/community/autoreact',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCommunityAutopostRoute =
  ApiPublicCommunityAutopostRouteImport.update({
    id: '/api/public/community/autopost',
    path: '/api/public/community/autopost',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCommunityAutocommentRoute =
  ApiPublicCommunityAutocommentRouteImport.update({
    id: '/api/public/community/autocomment',
    path: '/api/public/community/autocomment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalRulesRunRoute = ApiInternalRulesRunRouteImport.update({
  id: '/api/internal/rules/run',
  path: '/api/internal/rules/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalNotificationsDispatchRoute =
  ApiInternalNotificationsDispatchRouteImport.update({
    id: '/api/internal/notifications/dispatch',
    path: '/api/internal/notifications/dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalExtractionRunRoute =
  ApiInternalExtractionRunRouteImport.update({
    id: '/api/internal/extraction/run',
    path: '/api/internal/extraction/run',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalCallJobsRunRoute = ApiInternalCallJobsRunRouteImport.update({
  id: '/api/internal/call-jobs/run',
  path: '/api/internal/call-jobs/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioTwimlJobIdRoute =
  ApiPublicTwilioTwimlJobIdRouteImport.update({
    id: '/api/public/twilio/twiml/$jobId',
    path: '/api/public/twilio/twiml/$jobId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agencies': typeof AgenciesRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/home': typeof HomeRouteWithChildren
  '/local': typeof LocalRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/watch': typeof WatchRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/ask-logs': typeof AdminAskLogsRoute
  '/admin/emotion-rec': typeof AdminEmotionRecRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/investor-kpi': typeof AdminInvestorKpiRoute
  '/admin/organization-pipeline': typeof AdminOrganizationPipelineRoute
  '/admin/site-config': typeof AdminSiteConfigRoute
  '/admin/tips': typeof AdminTipsRouteWithChildren
  '/admin/voice-test': typeof AdminVoiceTestRoute
  '/community/write': typeof CommunityWriteRoute
  '/guardian/alerts': typeof GuardianAlertsRoute
  '/guardian/check-in': typeof GuardianCheckInRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/medications': typeof GuardianMedicationsRoute
  '/guardian/settings': typeof GuardianSettingsRoute
  '/home/invite': typeof HomeInviteRoute
  '/home/me': typeof HomeMeRoute
  '/home/passkeys': typeof HomePasskeysRoute
  '/home/settings': typeof HomeSettingsRoute
  '/invite/guardian': typeof InviteGuardianRoute
  '/partner/tasks': typeof PartnerTasksRoute
  '/policy/$slug': typeof PolicySlugRoute
  '/senior/home': typeof SeniorHomeRoute
  '/tips/$tipId': typeof TipsTipIdRoute
  '/admin/': typeof AdminIndexRoute
  '/care/': typeof CareIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/home/': typeof HomeIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/policy/': typeof PolicyIndexRoute
  '/tips/': typeof TipsIndexRoute
  '/admin/tips/$tipId': typeof AdminTipsTipIdRoute
  '/community/c/$slug': typeof CommunityCSlugRoute
  '/community/post/$postId': typeof CommunityPostPostIdRoute
  '/home/messages/$partnerId': typeof HomeMessagesPartnerIdRoute
  '/home/messages/': typeof HomeMessagesIndexRoute
  '/api/internal/call-jobs/run': typeof ApiInternalCallJobsRunRoute
  '/api/internal/extraction/run': typeof ApiInternalExtractionRunRoute
  '/api/internal/notifications/dispatch': typeof ApiInternalNotificationsDispatchRoute
  '/api/internal/rules/run': typeof ApiInternalRulesRunRoute
  '/api/public/community/autocomment': typeof ApiPublicCommunityAutocommentRoute
  '/api/public/community/autopost': typeof ApiPublicCommunityAutopostRoute
  '/api/public/community/autoreact': typeof ApiPublicCommunityAutoreactRoute
  '/api/public/ingest/run': typeof ApiPublicIngestRunRoute
  '/api/public/openai/session': typeof ApiPublicOpenaiSessionRoute
  '/api/public/openai/tool': typeof ApiPublicOpenaiToolRoute
  '/api/public/sms/inbound': typeof ApiPublicSmsInboundRoute
  '/api/public/sms/send-code': typeof ApiPublicSmsSendCodeRoute
  '/api/public/sms/verify-code': typeof ApiPublicSmsVerifyCodeRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/twiml/$jobId': typeof ApiPublicTwilioTwimlJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/local': typeof LocalRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/watch': typeof WatchRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/ask-logs': typeof AdminAskLogsRoute
  '/admin/emotion-rec': typeof AdminEmotionRecRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/investor-kpi': typeof AdminInvestorKpiRoute
  '/admin/organization-pipeline': typeof AdminOrganizationPipelineRoute
  '/admin/site-config': typeof AdminSiteConfigRoute
  '/admin/tips': typeof AdminTipsRouteWithChildren
  '/admin/voice-test': typeof AdminVoiceTestRoute
  '/community/write': typeof CommunityWriteRoute
  '/guardian/alerts': typeof GuardianAlertsRoute
  '/guardian/check-in': typeof GuardianCheckInRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/medications': typeof GuardianMedicationsRoute
  '/guardian/settings': typeof GuardianSettingsRoute
  '/home/invite': typeof HomeInviteRoute
  '/home/me': typeof HomeMeRoute
  '/home/passkeys': typeof HomePasskeysRoute
  '/home/settings': typeof HomeSettingsRoute
  '/invite/guardian': typeof InviteGuardianRoute
  '/partner/tasks': typeof PartnerTasksRoute
  '/policy/$slug': typeof PolicySlugRoute
  '/senior/home': typeof SeniorHomeRoute
  '/tips/$tipId': typeof TipsTipIdRoute
  '/admin': typeof AdminIndexRoute
  '/care': typeof CareIndexRoute
  '/community': typeof CommunityIndexRoute
  '/home': typeof HomeIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/policy': typeof PolicyIndexRoute
  '/tips': typeof TipsIndexRoute
  '/admin/tips/$tipId': typeof AdminTipsTipIdRoute
  '/community/c/$slug': typeof CommunityCSlugRoute
  '/community/post/$postId': typeof CommunityPostPostIdRoute
  '/home/messages/$partnerId': typeof HomeMessagesPartnerIdRoute
  '/home/messages': typeof HomeMessagesIndexRoute
  '/api/internal/call-jobs/run': typeof ApiInternalCallJobsRunRoute
  '/api/internal/extraction/run': typeof ApiInternalExtractionRunRoute
  '/api/internal/notifications/dispatch': typeof ApiInternalNotificationsDispatchRoute
  '/api/internal/rules/run': typeof ApiInternalRulesRunRoute
  '/api/public/community/autocomment': typeof ApiPublicCommunityAutocommentRoute
  '/api/public/community/autopost': typeof ApiPublicCommunityAutopostRoute
  '/api/public/community/autoreact': typeof ApiPublicCommunityAutoreactRoute
  '/api/public/ingest/run': typeof ApiPublicIngestRunRoute
  '/api/public/openai/session': typeof ApiPublicOpenaiSessionRoute
  '/api/public/openai/tool': typeof ApiPublicOpenaiToolRoute
  '/api/public/sms/inbound': typeof ApiPublicSmsInboundRoute
  '/api/public/sms/send-code': typeof ApiPublicSmsSendCodeRoute
  '/api/public/sms/verify-code': typeof ApiPublicSmsVerifyCodeRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/twiml/$jobId': typeof ApiPublicTwilioTwimlJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agencies': typeof AgenciesRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/home': typeof HomeRouteWithChildren
  '/local': typeof LocalRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/watch': typeof WatchRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/ask-logs': typeof AdminAskLogsRoute
  '/admin/emotion-rec': typeof AdminEmotionRecRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/investor-kpi': typeof AdminInvestorKpiRoute
  '/admin/organization-pipeline': typeof AdminOrganizationPipelineRoute
  '/admin/site-config': typeof AdminSiteConfigRoute
  '/admin/tips': typeof AdminTipsRouteWithChildren
  '/admin/voice-test': typeof AdminVoiceTestRoute
  '/community/write': typeof CommunityWriteRoute
  '/guardian/alerts': typeof GuardianAlertsRoute
  '/guardian/check-in': typeof GuardianCheckInRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/medications': typeof GuardianMedicationsRoute
  '/guardian/settings': typeof GuardianSettingsRoute
  '/home/invite': typeof HomeInviteRoute
  '/home/me': typeof HomeMeRoute
  '/home/passkeys': typeof HomePasskeysRoute
  '/home/settings': typeof HomeSettingsRoute
  '/invite/guardian': typeof InviteGuardianRoute
  '/partner/tasks': typeof PartnerTasksRoute
  '/policy/$slug': typeof PolicySlugRoute
  '/senior/home': typeof SeniorHomeRoute
  '/tips/$tipId': typeof TipsTipIdRoute
  '/admin/': typeof AdminIndexRoute
  '/care/': typeof CareIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/home/': typeof HomeIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/policy/': typeof PolicyIndexRoute
  '/tips/': typeof TipsIndexRoute
  '/admin/tips/$tipId': typeof AdminTipsTipIdRoute
  '/community/c/$slug': typeof CommunityCSlugRoute
  '/community/post/$postId': typeof CommunityPostPostIdRoute
  '/home/messages/$partnerId': typeof HomeMessagesPartnerIdRoute
  '/home/messages/': typeof HomeMessagesIndexRoute
  '/api/internal/call-jobs/run': typeof ApiInternalCallJobsRunRoute
  '/api/internal/extraction/run': typeof ApiInternalExtractionRunRoute
  '/api/internal/notifications/dispatch': typeof ApiInternalNotificationsDispatchRoute
  '/api/internal/rules/run': typeof ApiInternalRulesRunRoute
  '/api/public/community/autocomment': typeof ApiPublicCommunityAutocommentRoute
  '/api/public/community/autopost': typeof ApiPublicCommunityAutopostRoute
  '/api/public/community/autoreact': typeof ApiPublicCommunityAutoreactRoute
  '/api/public/ingest/run': typeof ApiPublicIngestRunRoute
  '/api/public/openai/session': typeof ApiPublicOpenaiSessionRoute
  '/api/public/openai/tool': typeof ApiPublicOpenaiToolRoute
  '/api/public/sms/inbound': typeof ApiPublicSmsInboundRoute
  '/api/public/sms/send-code': typeof ApiPublicSmsSendCodeRoute
  '/api/public/sms/verify-code': typeof ApiPublicSmsVerifyCodeRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/twiml/$jobId': typeof ApiPublicTwilioTwimlJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agencies'
    | '/auth'
    | '/checkin'
    | '/home'
    | '/local'
    | '/onboarding'
    | '/reset-password'
    | '/watch'
    | '/admin/agencies'
    | '/admin/alerts'
    | '/admin/ask-logs'
    | '/admin/emotion-rec'
    | '/admin/ingest'
    | '/admin/investor-kpi'
    | '/admin/organization-pipeline'
    | '/admin/site-config'
    | '/admin/tips'
    | '/admin/voice-test'
    | '/community/write'
    | '/guardian/alerts'
    | '/guardian/check-in'
    | '/guardian/dashboard'
    | '/guardian/medications'
    | '/guardian/settings'
    | '/home/invite'
    | '/home/me'
    | '/home/passkeys'
    | '/home/settings'
    | '/invite/guardian'
    | '/partner/tasks'
    | '/policy/$slug'
    | '/senior/home'
    | '/tips/$tipId'
    | '/admin/'
    | '/care/'
    | '/community/'
    | '/home/'
    | '/partner/'
    | '/policy/'
    | '/tips/'
    | '/admin/tips/$tipId'
    | '/community/c/$slug'
    | '/community/post/$postId'
    | '/home/messages/$partnerId'
    | '/home/messages/'
    | '/api/internal/call-jobs/run'
    | '/api/internal/extraction/run'
    | '/api/internal/notifications/dispatch'
    | '/api/internal/rules/run'
    | '/api/public/community/autocomment'
    | '/api/public/community/autopost'
    | '/api/public/community/autoreact'
    | '/api/public/ingest/run'
    | '/api/public/openai/session'
    | '/api/public/openai/tool'
    | '/api/public/sms/inbound'
    | '/api/public/sms/send-code'
    | '/api/public/sms/verify-code'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/status'
    | '/api/public/twilio/twiml/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agencies'
    | '/auth'
    | '/checkin'
    | '/local'
    | '/onboarding'
    | '/reset-password'
    | '/watch'
    | '/admin/agencies'
    | '/admin/alerts'
    | '/admin/ask-logs'
    | '/admin/emotion-rec'
    | '/admin/ingest'
    | '/admin/investor-kpi'
    | '/admin/organization-pipeline'
    | '/admin/site-config'
    | '/admin/tips'
    | '/admin/voice-test'
    | '/community/write'
    | '/guardian/alerts'
    | '/guardian/check-in'
    | '/guardian/dashboard'
    | '/guardian/medications'
    | '/guardian/settings'
    | '/home/invite'
    | '/home/me'
    | '/home/passkeys'
    | '/home/settings'
    | '/invite/guardian'
    | '/partner/tasks'
    | '/policy/$slug'
    | '/senior/home'
    | '/tips/$tipId'
    | '/admin'
    | '/care'
    | '/community'
    | '/home'
    | '/partner'
    | '/policy'
    | '/tips'
    | '/admin/tips/$tipId'
    | '/community/c/$slug'
    | '/community/post/$postId'
    | '/home/messages/$partnerId'
    | '/home/messages'
    | '/api/internal/call-jobs/run'
    | '/api/internal/extraction/run'
    | '/api/internal/notifications/dispatch'
    | '/api/internal/rules/run'
    | '/api/public/community/autocomment'
    | '/api/public/community/autopost'
    | '/api/public/community/autoreact'
    | '/api/public/ingest/run'
    | '/api/public/openai/session'
    | '/api/public/openai/tool'
    | '/api/public/sms/inbound'
    | '/api/public/sms/send-code'
    | '/api/public/sms/verify-code'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/status'
    | '/api/public/twilio/twiml/$jobId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agencies'
    | '/auth'
    | '/checkin'
    | '/home'
    | '/local'
    | '/onboarding'
    | '/reset-password'
    | '/watch'
    | '/admin/agencies'
    | '/admin/alerts'
    | '/admin/ask-logs'
    | '/admin/emotion-rec'
    | '/admin/ingest'
    | '/admin/investor-kpi'
    | '/admin/organization-pipeline'
    | '/admin/site-config'
    | '/admin/tips'
    | '/admin/voice-test'
    | '/community/write'
    | '/guardian/alerts'
    | '/guardian/check-in'
    | '/guardian/dashboard'
    | '/guardian/medications'
    | '/guardian/settings'
    | '/home/invite'
    | '/home/me'
    | '/home/passkeys'
    | '/home/settings'
    | '/invite/guardian'
    | '/partner/tasks'
    | '/policy/$slug'
    | '/senior/home'
    | '/tips/$tipId'
    | '/admin/'
    | '/care/'
    | '/community/'
    | '/home/'
    | '/partner/'
    | '/policy/'
    | '/tips/'
    | '/admin/tips/$tipId'
    | '/community/c/$slug'
    | '/community/post/$postId'
    | '/home/messages/$partnerId'
    | '/home/messages/'
    | '/api/internal/call-jobs/run'
    | '/api/internal/extraction/run'
    | '/api/internal/notifications/dispatch'
    | '/api/internal/rules/run'
    | '/api/public/community/autocomment'
    | '/api/public/community/autopost'
    | '/api/public/community/autoreact'
    | '/api/public/ingest/run'
    | '/api/public/openai/session'
    | '/api/public/openai/tool'
    | '/api/public/sms/inbound'
    | '/api/public/sms/send-code'
    | '/api/public/sms/verify-code'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/status'
    | '/api/public/twilio/twiml/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgenciesRoute: typeof AgenciesRoute
  AuthRoute: typeof AuthRoute
  CheckinRoute: typeof CheckinRoute
  HomeRoute: typeof HomeRouteWithChildren
  LocalRoute: typeof LocalRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WatchRoute: typeof WatchRoute
  CommunityWriteRoute: typeof CommunityWriteRoute
  GuardianAlertsRoute: typeof GuardianAlertsRoute
  GuardianCheckInRoute: typeof GuardianCheckInRoute
  GuardianDashboardRoute: typeof GuardianDashboardRoute
  GuardianMedicationsRoute: typeof GuardianMedicationsRoute
  GuardianSettingsRoute: typeof GuardianSettingsRoute
  InviteGuardianRoute: typeof InviteGuardianRoute
  PartnerTasksRoute: typeof PartnerTasksRoute
  PolicySlugRoute: typeof PolicySlugRoute
  SeniorHomeRoute: typeof SeniorHomeRoute
  TipsTipIdRoute: typeof TipsTipIdRoute
  CareIndexRoute: typeof CareIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
  PolicyIndexRoute: typeof PolicyIndexRoute
  TipsIndexRoute: typeof TipsIndexRoute
  CommunityCSlugRoute: typeof CommunityCSlugRoute
  CommunityPostPostIdRoute: typeof CommunityPostPostIdRoute
  ApiInternalCallJobsRunRoute: typeof ApiInternalCallJobsRunRoute
  ApiInternalExtractionRunRoute: typeof ApiInternalExtractionRunRoute
  ApiInternalNotificationsDispatchRoute: typeof ApiInternalNotificationsDispatchRoute
  ApiInternalRulesRunRoute: typeof ApiInternalRulesRunRoute
  ApiPublicCommunityAutocommentRoute: typeof ApiPublicCommunityAutocommentRoute
  ApiPublicCommunityAutopostRoute: typeof ApiPublicCommunityAutopostRoute
  ApiPublicCommunityAutoreactRoute: typeof ApiPublicCommunityAutoreactRoute
  ApiPublicIngestRunRoute: typeof ApiPublicIngestRunRoute
  ApiPublicOpenaiSessionRoute: typeof ApiPublicOpenaiSessionRoute
  ApiPublicOpenaiToolRoute: typeof ApiPublicOpenaiToolRoute
  ApiPublicSmsInboundRoute: typeof ApiPublicSmsInboundRoute
  ApiPublicSmsSendCodeRoute: typeof ApiPublicSmsSendCodeRoute
  ApiPublicSmsVerifyCodeRoute: typeof ApiPublicSmsVerifyCodeRoute
  ApiPublicTwilioRecordingRoute: typeof ApiPublicTwilioRecordingRoute
  ApiPublicTwilioStatusRoute: typeof ApiPublicTwilioStatusRoute
  ApiPublicTwilioTwimlJobIdRoute: typeof ApiPublicTwilioTwimlJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips/': {
      id: '/tips/'
      path: '/tips'
      fullPath: '/tips/'
      preLoaderRoute: typeof TipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/': {
      id: '/policy/'
      path: '/policy'
      fullPath: '/policy/'
      preLoaderRoute: typeof PolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care/': {
      id: '/care/'
      path: '/care'
      fullPath: '/care/'
      preLoaderRoute: typeof CareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tips/$tipId': {
      id: '/tips/$tipId'
      path: '/tips/$tipId'
      fullPath: '/tips/$tipId'
      preLoaderRoute: typeof TipsTipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senior/home': {
      id: '/senior/home'
      path: '/senior/home'
      fullPath: '/senior/home'
      preLoaderRoute: typeof SeniorHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/$slug': {
      id: '/policy/$slug'
      path: '/policy/$slug'
      fullPath: '/policy/$slug'
      preLoaderRoute: typeof PolicySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/tasks': {
      id: '/partner/tasks'
      path: '/partner/tasks'
      fullPath: '/partner/tasks'
      preLoaderRoute: typeof PartnerTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/guardian': {
      id: '/invite/guardian'
      path: '/invite/guardian'
      fullPath: '/invite/guardian'
      preLoaderRoute: typeof InviteGuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/settings': {
      id: '/home/settings'
      path: '/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/passkeys': {
      id: '/home/passkeys'
      path: '/passkeys'
      fullPath: '/home/passkeys'
      preLoaderRoute: typeof HomePasskeysRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/me': {
      id: '/home/me'
      path: '/me'
      fullPath: '/home/me'
      preLoaderRoute: typeof HomeMeRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/invite': {
      id: '/home/invite'
      path: '/invite'
      fullPath: '/home/invite'
      preLoaderRoute: typeof HomeInviteRouteImport
      parentRoute: typeof HomeRoute
    }
    '/guardian/settings': {
      id: '/guardian/settings'
      path: '/guardian/settings'
      fullPath: '/guardian/settings'
      preLoaderRoute: typeof GuardianSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/medications': {
      id: '/guardian/medications'
      path: '/guardian/medications'
      fullPath: '/guardian/medications'
      preLoaderRoute: typeof GuardianMedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/dashboard': {
      id: '/guardian/dashboard'
      path: '/guardian/dashboard'
      fullPath: '/guardian/dashboard'
      preLoaderRoute: typeof GuardianDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/check-in': {
      id: '/guardian/check-in'
      path: '/guardian/check-in'
      fullPath: '/guardian/check-in'
      preLoaderRoute: typeof GuardianCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/alerts': {
      id: '/guardian/alerts'
      path: '/guardian/alerts'
      fullPath: '/guardian/alerts'
      preLoaderRoute: typeof GuardianAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/write': {
      id: '/community/write'
      path: '/community/write'
      fullPath: '/community/write'
      preLoaderRoute: typeof CommunityWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/voice-test': {
      id: '/admin/voice-test'
      path: '/voice-test'
      fullPath: '/admin/voice-test'
      preLoaderRoute: typeof AdminVoiceTestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tips': {
      id: '/admin/tips'
      path: '/tips'
      fullPath: '/admin/tips'
      preLoaderRoute: typeof AdminTipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-config': {
      id: '/admin/site-config'
      path: '/site-config'
      fullPath: '/admin/site-config'
      preLoaderRoute: typeof AdminSiteConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization-pipeline': {
      id: '/admin/organization-pipeline'
      path: '/organization-pipeline'
      fullPath: '/admin/organization-pipeline'
      preLoaderRoute: typeof AdminOrganizationPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/investor-kpi': {
      id: '/admin/investor-kpi'
      path: '/investor-kpi'
      fullPath: '/admin/investor-kpi'
      preLoaderRoute: typeof AdminInvestorKpiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ingest': {
      id: '/admin/ingest'
      path: '/ingest'
      fullPath: '/admin/ingest'
      preLoaderRoute: typeof AdminIngestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emotion-rec': {
      id: '/admin/emotion-rec'
      path: '/emotion-rec'
      fullPath: '/admin/emotion-rec'
      preLoaderRoute: typeof AdminEmotionRecRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ask-logs': {
      id: '/admin/ask-logs'
      path: '/ask-logs'
      fullPath: '/admin/ask-logs'
      preLoaderRoute: typeof AdminAskLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agencies': {
      id: '/admin/agencies'
      path: '/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof AdminAgenciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/home/messages/': {
      id: '/home/messages/'
      path: '/messages'
      fullPath: '/home/messages/'
      preLoaderRoute: typeof HomeMessagesIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/messages/$partnerId': {
      id: '/home/messages/$partnerId'
      path: '/messages/$partnerId'
      fullPath: '/home/messages/$partnerId'
      preLoaderRoute: typeof HomeMessagesPartnerIdRouteImport
      parentRoute: typeof HomeRoute
    }
    '/community/post/$postId': {
      id: '/community/post/$postId'
      path: '/community/post/$postId'
      fullPath: '/community/post/$postId'
      preLoaderRoute: typeof CommunityPostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/c/$slug': {
      id: '/community/c/$slug'
      path: '/community/c/$slug'
      fullPath: '/community/c/$slug'
      preLoaderRoute: typeof CommunityCSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tips/$tipId': {
      id: '/admin/tips/$tipId'
      path: '/$tipId'
      fullPath: '/admin/tips/$tipId'
      preLoaderRoute: typeof AdminTipsTipIdRouteImport
      parentRoute: typeof AdminTipsRoute
    }
    '/api/public/twilio/status': {
      id: '/api/public/twilio/status'
      path: '/api/public/twilio/status'
      fullPath: '/api/public/twilio/status'
      preLoaderRoute: typeof ApiPublicTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/recording': {
      id: '/api/public/twilio/recording'
      path: '/api/public/twilio/recording'
      fullPath: '/api/public/twilio/recording'
      preLoaderRoute: typeof ApiPublicTwilioRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms/verify-code': {
      id: '/api/public/sms/verify-code'
      path: '/api/public/sms/verify-code'
      fullPath: '/api/public/sms/verify-code'
      preLoaderRoute: typeof ApiPublicSmsVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms/send-code': {
      id: '/api/public/sms/send-code'
      path: '/api/public/sms/send-code'
      fullPath: '/api/public/sms/send-code'
      preLoaderRoute: typeof ApiPublicSmsSendCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms/inbound': {
      id: '/api/public/sms/inbound'
      path: '/api/public/sms/inbound'
      fullPath: '/api/public/sms/inbound'
      preLoaderRoute: typeof ApiPublicSmsInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openai/tool': {
      id: '/api/public/openai/tool'
      path: '/api/public/openai/tool'
      fullPath: '/api/public/openai/tool'
      preLoaderRoute: typeof ApiPublicOpenaiToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openai/session': {
      id: '/api/public/openai/session'
      path: '/api/public/openai/session'
      fullPath: '/api/public/openai/session'
      preLoaderRoute: typeof ApiPublicOpenaiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/run': {
      id: '/api/public/ingest/run'
      path: '/api/public/ingest/run'
      fullPath: '/api/public/ingest/run'
      preLoaderRoute: typeof ApiPublicIngestRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/community/autoreact': {
      id: '/api/public/community/autoreact'
      path: '/api/public/community/autoreact'
      fullPath: '/api/public/community/autoreact'
      preLoaderRoute: typeof ApiPublicCommunityAutoreactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/community/autopost': {
      id: '/api/public/community/autopost'
      path: '/api/public/community/autopost'
      fullPath: '/api/public/community/autopost'
      preLoaderRoute: typeof ApiPublicCommunityAutopostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/community/autocomment': {
      id: '/api/public/community/autocomment'
      path: '/api/public/community/autocomment'
      fullPath: '/api/public/community/autocomment'
      preLoaderRoute: typeof ApiPublicCommunityAutocommentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/rules/run': {
      id: '/api/internal/rules/run'
      path: '/api/internal/rules/run'
      fullPath: '/api/internal/rules/run'
      preLoaderRoute: typeof ApiInternalRulesRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/notifications/dispatch': {
      id: '/api/internal/notifications/dispatch'
      path: '/api/internal/notifications/dispatch'
      fullPath: '/api/internal/notifications/dispatch'
      preLoaderRoute: typeof ApiInternalNotificationsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/extraction/run': {
      id: '/api/internal/extraction/run'
      path: '/api/internal/extraction/run'
      fullPath: '/api/internal/extraction/run'
      preLoaderRoute: typeof ApiInternalExtractionRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/call-jobs/run': {
      id: '/api/internal/call-jobs/run'
      path: '/api/internal/call-jobs/run'
      fullPath: '/api/internal/call-jobs/run'
      preLoaderRoute: typeof ApiInternalCallJobsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/twiml/$jobId': {
      id: '/api/public/twilio/twiml/$jobId'
      path: '/api/public/twilio/twiml/$jobId'
      fullPath: '/api/public/twilio/twiml/$jobId'
      preLoaderRoute: typeof ApiPublicTwilioTwimlJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminTipsRouteChildren {
  AdminTipsTipIdRoute: typeof AdminTipsTipIdRoute
}

const AdminTipsRouteChildren: AdminTipsRouteChildren = {
  AdminTipsTipIdRoute: AdminTipsTipIdRoute,
}

const AdminTipsRouteWithChildren = AdminTipsRoute._addFileChildren(
  AdminTipsRouteChildren,
)

interface AdminRouteChildren {
  AdminAgenciesRoute: typeof AdminAgenciesRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAskLogsRoute: typeof AdminAskLogsRoute
  AdminEmotionRecRoute: typeof AdminEmotionRecRoute
  AdminIngestRoute: typeof AdminIngestRoute
  AdminInvestorKpiRoute: typeof AdminInvestorKpiRoute
  AdminOrganizationPipelineRoute: typeof AdminOrganizationPipelineRoute
  AdminSiteConfigRoute: typeof AdminSiteConfigRoute
  AdminTipsRoute: typeof AdminTipsRouteWithChildren
  AdminVoiceTestRoute: typeof AdminVoiceTestRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgenciesRoute: AdminAgenciesRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAskLogsRoute: AdminAskLogsRoute,
  AdminEmotionRecRoute: AdminEmotionRecRoute,
  AdminIngestRoute: AdminIngestRoute,
  AdminInvestorKpiRoute: AdminInvestorKpiRoute,
  AdminOrganizationPipelineRoute: AdminOrganizationPipelineRoute,
  AdminSiteConfigRoute: AdminSiteConfigRoute,
  AdminTipsRoute: AdminTipsRouteWithChildren,
  AdminVoiceTestRoute: AdminVoiceTestRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HomeRouteChildren {
  HomeInviteRoute: typeof HomeInviteRoute
  HomeMeRoute: typeof HomeMeRoute
  HomePasskeysRoute: typeof HomePasskeysRoute
  HomeSettingsRoute: typeof HomeSettingsRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomeMessagesPartnerIdRoute: typeof HomeMessagesPartnerIdRoute
  HomeMessagesIndexRoute: typeof HomeMessagesIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeInviteRoute: HomeInviteRoute,
  HomeMeRoute: HomeMeRoute,
  HomePasskeysRoute: HomePasskeysRoute,
  HomeSettingsRoute: HomeSettingsRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeMessagesPartnerIdRoute: HomeMessagesPartnerIdRoute,
  HomeMessagesIndexRoute: HomeMessagesIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgenciesRoute: AgenciesRoute,
  AuthRoute: AuthRoute,
  CheckinRoute: CheckinRoute,
  HomeRoute: HomeRouteWithChildren,
  LocalRoute: LocalRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WatchRoute: WatchRoute,
  CommunityWriteRoute: CommunityWriteRoute,
  GuardianAlertsRoute: GuardianAlertsRoute,
  GuardianCheckInRoute: GuardianCheckInRoute,
  GuardianDashboardRoute: GuardianDashboardRoute,
  GuardianMedicationsRoute: GuardianMedicationsRoute,
  GuardianSettingsRoute: GuardianSettingsRoute,
  InviteGuardianRoute: InviteGuardianRoute,
  PartnerTasksRoute: PartnerTasksRoute,
  PolicySlugRoute: PolicySlugRoute,
  SeniorHomeRoute: SeniorHomeRoute,
  TipsTipIdRoute: TipsTipIdRoute,
  CareIndexRoute: CareIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  PartnerIndexRoute: PartnerIndexRoute,
  PolicyIndexRoute: PolicyIndexRoute,
  TipsIndexRoute: TipsIndexRoute,
  CommunityCSlugRoute: CommunityCSlugRoute,
  CommunityPostPostIdRoute: CommunityPostPostIdRoute,
  ApiInternalCallJobsRunRoute: ApiInternalCallJobsRunRoute,
  ApiInternalExtractionRunRoute: ApiInternalExtractionRunRoute,
  ApiInternalNotificationsDispatchRoute: ApiInternalNotificationsDispatchRoute,
  ApiInternalRulesRunRoute: ApiInternalRulesRunRoute,
  ApiPublicCommunityAutocommentRoute: ApiPublicCommunityAutocommentRoute,
  ApiPublicCommunityAutopostRoute: ApiPublicCommunityAutopostRoute,
  ApiPublicCommunityAutoreactRoute: ApiPublicCommunityAutoreactRoute,
  ApiPublicIngestRunRoute: ApiPublicIngestRunRoute,
  ApiPublicOpenaiSessionRoute: ApiPublicOpenaiSessionRoute,
  ApiPublicOpenaiToolRoute: ApiPublicOpenaiToolRoute,
  ApiPublicSmsInboundRoute: ApiPublicSmsInboundRoute,
  ApiPublicSmsSendCodeRoute: ApiPublicSmsSendCodeRoute,
  ApiPublicSmsVerifyCodeRoute: ApiPublicSmsVerifyCodeRoute,
  ApiPublicTwilioRecordingRoute: ApiPublicTwilioRecordingRoute,
  ApiPublicTwilioStatusRoute: ApiPublicTwilioStatusRoute,
  ApiPublicTwilioTwimlJobIdRoute: ApiPublicTwilioTwimlJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
